#!/bin/sh
set -e

if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
    deb-systemd-helper mask --runtime modem-kick
fi

# Automatically added by dh_installsystemd/13.11.1~bpo11+1
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
        deb-systemd-invoke stop 'modem-kick.service' >/dev/null || true
fi
# End automatically added section

